### ISSUE TITLE
Not all icons work !

### ISSUE THREAD

**Issue by Sourack** [davidhsianturi/blade-bootstrap-icons#16]
![image](https://user-images.githubusercontent.com/20821366/95465427-243a5f80-0949-11eb-81e4-bb3f98cc519b.png)

For example: «x-bi-key»«/x-bi-key» is'nt working but «x-bi-wallet2»«/x-bi-wallet2» is working. I didn't understand lol.

I try with some others icons and I have the same issue: somes icons aren't working.

My setup: Laravel 8 with blade

**Comment by davidhsianturi** [comment]
it's working for me in Laravel 8

<img width="191" alt="Screen Shot 2020-10-09 at 15 35 37" src="https://user-images.githubusercontent.com/26449835/95561790-7660ab00-0a45-11eb-9219-5f638f3b6967.png">
<img width="579" alt="Screen Shot 2020-10-09 at 15 36 27" src="https://user-images.githubusercontent.com/26449835/95561795-78c30500-0a45-11eb-92cf-1a5baebcf779.png">

**Comment by Sourack** [comment]
Well ok I did some testing and it's not my code. I made a fresh new installation of laravel and I have exactly the same problem. I don't know what the problem is. Maybe my php version I didn't know. It's weird because everything else works very well.

**Comment by davidhsianturi** [comment]
@Sourack try the latest release, closing this for now.
