### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by rinodrummer** [davidhsianturi/blade-bootstrap-icons#61]
Hi, I was trying to update a project to Laravel 9 but had to revert.

Any plans on supporting it or may a migration guide be supplied?

Thanks!

**Comment by muffycompo** [comment]
Submitted a PR to add Laravel 9 support as referenced here #65

**Comment by half-fiza** [comment]
Hello! eagerly waiting for Laravel 9 support. The PR is closed now :( . Tentatively what date will it be done?

**Comment by muffycompo** [comment]
> Hello! eagerly waiting for Laravel 9 support. The PR is closed now :( . Tentatively what date will it be done?

Hi @half-fiza, I resubmitted the PR here (#71) so hopefully when @davidhsianturi is able to review it.

**Comment by half-fiza** [comment]
Eagerly waiting!! @davidhsianturi  to review it!.

**Comment by davidhsianturi** [comment]
#71  Done! thanks
